# Generated by Django 4.2.4 on 2024-08-22 14:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_about_image_contact_image_service_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='Banner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('page_name', models.CharField(choices=[('service_detail', 'Service Detail Page'), ('service', 'Service Page'), ('about', 'About Page'), ('about_detail', 'About Detail Page')], max_length=50, unique=True)),
                ('image', models.ImageField(upload_to='banners/')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True, null=True)),
            ],
        ),
    ]
