# Generated by Django 4.2.4 on 2024-10-12 11:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_alter_banner_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='carouselitem',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='carouselitem',
            name='title',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
