# Generated by Django 4.2.4 on 2024-10-22 13:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_alter_carouselitem_description_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='SubAbout',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('icon', models.CharField(max_length=200)),
                ('content', models.TextField()),
            ],
        ),
    ]
