# Generated by Django 4.2.4 on 2024-10-28 07:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_newslettersubscription_quoterequest_delete_subabout_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='carouselitem',
            name='subtitle',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='carouselitem',
            name='description',
            field=models.TextField(null=True),
        ),
    ]
